version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - npm install -g aws-cdk
      - python3 -m venv .env
      - chmod +x .env/bin/activate
      - . .env/bin/activate
      - pip3 install -r requirements.txt
      
  pre_build:
    commands:
      - echo dependancies
 
      - pip3 install Requests
      - pip3 install BeautifulSoup4
      - pip3 install boto3

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo finished

artifacts:
  discard-paths: no
  files:
    - "**/*"
