version: 0.2
phases:
  install:
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - echo 
      #pip3 install --upgrade aws-sam-cli
      
      # pip3 install cdk
      # pip3 install Requests, BeautifulSoup4, boto3
      
  pre_build:
    commands:
      - echo

  build:
    commands:
      - echo
      # cdk deploy --force #??

  post_build:
    commands:
      - echo


